set_property SRC_FILE_INFO {cfile:C:/Users/brian/source/repos/hybridmachine/learning/FPGA/Blink_Basys3/Blink_Basys3.srcs/constrs_1/new/Basys3.xdc rfile:../../../Blink_Basys3.srcs/constrs_1/new/Basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports OUT_HIGH]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3 [get_ports OUT_LOW]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports RESET]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports CLOCK_IN]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports NOT_LOW]
