# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.srcs/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK.xci
# IP: The module: 'INCLKtoSYSCLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.srcs/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK.xci
# IP: The module: 'INCLKtoSYSCLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/brian/source/repos/hybridmachine/learning/FPGA/SevenSegmentDisplay/SevenSegmentDisplay.gen/sources_1/ip/INCLKtoSYSCLK/INCLKtoSYSCLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INCLKtoSYSCLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
